# NumPy数据存取与函数



In [3]:
import numpy as np

## 数据的CSV文件存取
### 将数据写入csv
np.savetxt(frame,array, fmt = "%.18e", delimiter = None)
- frame: 文件，字符串或产生器，可以是.gz或.bz2压缩文件 
- array: 存入文件的数组
- fmt: 写入文件的格式，例如：%d%2f%.18e
- delimiter: 分割字符串，默认是任何空格

In [4]:
a = np.arange(100).reshape(5,20)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [10]:
np.savetxt("a.csv", a, fmt = "%d", delimiter = ",")


### 读取csv数据
np.loadtxt(frame, dtype = np.float, delimiter = None, unpack =  False)
- frame: 文件，字符串或产生器，可以是.gz或.bz2的压缩文件
- dtype: 数据类型，可选
- delimiter: 分割字符串, 默认是任何空格
- unpack: 如果True, 读入属性将写入不同变量

#### np.loadtxt

In [9]:
b = np.loadtxt("a.csv",delimiter = ",")
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

## CSV文件的局限性
CSV只能有效存储一维和二维数组
np.savetxt(); np.loadtxt()只能有效存取一维和二维数组


# 多维数据的存取
 

## 任意维度数据如何存取

### 存储任意维度的数据
a.tofile(frame, sep = '', format = '%s')

- frame: 文件，字符串
- sep: 数据分割字符串，如果是空串
- format: 写入数据的格式



In [12]:
a  = np.arange(100).reshape(5,10,2)
a.tofile("b.dat", sep = ",", format = "%d")

In [16]:
a  = np.arange(100).reshape(5,10,2)
a.tofile("c.dat", sep = ",", format = "%s")

In [18]:
a  = np.arange(100).reshape(5,10,2)
a.tofile("d.dat",format = "%d")

### 读取任意维度的数据

np.fromfile(frame, dtype = float, count = -1, sep = '')

- frame: 文件，字符串
- dtype: 读取的数据类型
- count: 读入元素个数，-1表示读入整个文件
- sep: 数据分割字符串，如果是空，写入文件为二进制

In [20]:
a = np.arange(100).reshape(5,10,2)
c = np.fromfile("b.dat", dtype = np.int, sep = ',')

In [22]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
c = c.reshape(5,10,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

## Numpy的便携文件存取
np.save(fname, array) 或 np.savez(fname, array)
- fname : 文件名，以.npy为扩展名，压缩扩展名为.npz
- array : 数组变量

np.load(fname)
- frame : 文件名，以.npy为扩展名，压缩扩展名为.np

## Numpy的随机数函数子库(1)
1. np.random.*

- np.random.rand(d0,d1,..,dn): 根据d0‐dn创建随机数数组，浮点数，[0,1)，均匀分布
- randn(d0,d1,..,dn): 根据d0‐dn创建随机数数组，标准正态分布
- randint(low[, high, hape]): 根据shape创建随机整数或整数数组，范围是[low, high)
- seed(s): 随机数种子，s是给定的种子值

2. shuffle(a): 根据数组a的第1轴进行随排列，改变数组x

3. permutation(a): 根据数组a的第1轴产生一个新的乱序数组，不改变数组x

4. choice(a[,size,replace,p]): 从一维数组a中以概率p抽取元素，形成size形状新数组 replace表示是否可以重用元素，默认为False




In [25]:
a = np.random.rand(3,4,5)
a

array([[[0.73883565, 0.58047375, 0.36821846, 0.97755608, 0.74360352],
        [0.17661563, 0.49229834, 0.34069352, 0.94920273, 0.15548118],
        [0.1017372 , 0.96962368, 0.16689454, 0.55118249, 0.62485232],
        [0.92884459, 0.15282691, 0.70151331, 0.85223461, 0.52845874]],

       [[0.4534344 , 0.39107026, 0.23713559, 0.28304529, 0.28509618],
        [0.3992585 , 0.02908636, 0.88786779, 0.62414144, 0.24096733],
        [0.83620009, 0.00849905, 0.13744113, 0.17629737, 0.09461948],
        [0.32535489, 0.40523021, 0.97742531, 0.09469144, 0.99772911]],

       [[0.3193099 , 0.93189123, 0.44415005, 0.41070573, 0.44251762],
        [0.86773445, 0.86760533, 0.65864075, 0.00420576, 0.375222  ],
        [0.18931522, 0.52832532, 0.93698867, 0.60053303, 0.23884534],
        [0.77351486, 0.06917383, 0.06920655, 0.80508893, 0.23894102]]])

In [27]:
a = np.random.randn(3,4,5)
a 

array([[[ 0.74906016,  0.29824995,  0.45628224, -0.5498135 ,
         -0.58904782],
        [-0.48142787,  2.06016124, -0.93462677,  0.02761313,
         -0.86064853],
        [-1.41489108, -1.09529722,  0.42516742,  0.73724758,
         -0.49345464],
        [ 0.64350045, -1.38029344,  0.33700726,  0.79217334,
          1.33118453]],

       [[-0.30045438,  0.05404906,  1.32741997,  0.22525809,
         -2.03507458],
        [-0.24912726,  0.42753722,  0.64064527, -0.0829262 ,
         -1.39362727],
        [-0.55408027, -3.10766056,  0.10816584,  0.75841612,
         -1.36249755],
        [-0.20393668,  0.03141496,  1.24909753, -0.92855672,
         -3.61022711]],

       [[-1.42550887,  1.41567397,  0.47245951, -0.40803658,
          2.05888836],
        [ 1.37209608, -0.1730004 ,  0.45952043,  0.47492323,
          0.89813978],
        [-0.38369122,  1.23482431, -1.56828984, -2.03345711,
         -1.64276572],
        [ 0.07173082,  1.32225263, -1.04007969,  0.13206231,
          0

In [29]:
b = np.random.randint(100,200,(3,4))
b

array([[120, 116, 187, 159],
       [121, 120, 126, 185],
       [188, 132, 182, 143]])

In [30]:
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [33]:
a = np.random.randint(100,200,(3,4))
a

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

## Numpy的随机数函数子库(2)

1. shuffle(a): 根据数组a的第1轴进行随排列，改变数组x

2. permutation(a): 根据数组a的第1轴产生一个新的乱序数组，不改变数组x

3. choice(a[,size,replace,p]): 从一维数组a中以概率p抽取元素，形成size形状新数组 replace表示是否可以重用元素，默认为False


In [35]:
np.random.shuffle(a)
a

array([[162, 133, 172, 178],
       [116, 111, 154, 188],
       [149, 151, 154, 177]])

In [36]:
a = np.random.randint(100,200,(3,4))
a

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [42]:
np.random.permutation(a)

array([[130, 189, 112, 165],
       [113, 192, 186, 130],
       [131, 157, 136, 127]])

In [43]:
a

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

## Numpy的随机数函数子库(3)
- uniform(low, high, size): 产生具有均匀分布的数组，low起始值，high结束值，size形状
- normal(loc, scale, size):具有正态分布的数组，loc均值，scale标准差， size形状
- poissom(lam, size): 