# ndarray数据格式

In [3]:
import numpy as np

## 使用循环

In [4]:

def pySum():
    a = [0,1,2,3,4]
    b = [9,8,7,6,5]
    c = []

    for i in range(len(a)):
        c.append(a[i]**2+b[i]**3)
    return c
print(pySum())


[729, 513, 347, 225, 141]


## 使用Numpy
- Numpy去掉了循环，提高了效率。
- 数组对象采用相同的数据类型，有助于节省运算和存储空间。


In [5]:
def npSum():
    a = np.array([0,1,2,3,4])
    b = np.array([9,8,7,6,5])
    c = a**2+b**3

    return c 
print(npSum())

[729 513 347 225 141]


# ndarray是什么
一个多维数组的对象，由两部分组成:
- 实际的数据
- 描述这些数据的元数据

ndarray要求所有元素类型相同，也就是同质；与list相同，下标index是从0开始的。

## ndarray例子

In [6]:
# 生成一个nparray数组
a = np.array([[0,1,2,3,4],[9,8,7,6,5]])



In [7]:
# 输出为[]性质，元素由空格分割
# axis: 轴，保存数据的维度
# rank：秩， 轴的数量
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

## ndarray对象的属性
- `.ndim`: 轴，保存数据的维度
- `.shape`: ndarray对象的尺度，对于矩阵，n行m列
- `.size`: ndarray对象元素的个数，相当于`.shape`中n*m的值
- `.dtype`: ndarray对象的元素类型
- `.itemsize`: ndarray对象中每个元素的大小，以字节为单位

### 例子

In [8]:
# .ndim: 轴，保存数据的维度
a.ndim

2

In [9]:
# .shape: ndarray对象的尺度，对于矩阵，n行m列
a.shape

(2, 5)

In [10]:
# .size: ndarray对象元素的个数，相当于.shape中n*m的值
a.size

10

In [11]:
# .dtype: ndarray对象的元素类型
a.dtype

dtype('int64')

In [12]:
# .itemsize: ndarray对象中每个元素的大小，以字节为单位
a.itemsize

8

## ndarray的元素类型
- bool：布尔值，True或False
- intc：与C语言的int类型一致，一般是int32或int64，取决于运行的电脑
- intp：用于索引的整数，与C语言的ssize_t一致，一般是int32或int64
- inti, i =（8,16,32,64）: i位长度的整数，取值范围[$-2^{i-1}$,$2^{i-1}-1$]
在python语法中，仅支持int，float，complex。但ndarray的出现补充了python可以处理的数据类型，有处于程序员对程序的优化，评估。


In [13]:
# ndarray数组可以由非同质对象构成
x = np.array([[0,1,2,3,4],[9,8,7,6]])

In [14]:
x.shape

(2,)

In [15]:
x.dtype

dtype('O')

In [16]:
x # 非同质ndarray对象无法有效numpy优质，尽量不用

array([list([0, 1, 2, 3, 4]), list([9, 8, 7, 6])], dtype=object)

# ndarray数组的创建方法
## 从Python中的列表、元组等类型创建ndarray数组
### 从list创建数组


In [27]:
# x = np.array(list/tuple)
x = np.array([0,1,2,3])
print(x)

[0 1 2 3]


### 从元组创建数组

In [28]:
x = np.array((4,5,6,7))
print(x)

[4 5 6 7]


### 从列表和元组的混合数据创建数组

In [29]:
x = np.array([[1,2],[3,3],(0.1,0.3)])
print(x)

[[1.  2. ]
 [3.  3. ]
 [0.1 0.3]]


## 使用NumPy中函数创建ndarray数组
- np.arange(n): 类似range()函数，返回ndarray类型，元素从0到n‐1
- np.ones(shape): 根据shape生成一个全1数组，shape是元组类型
- np.full(shape,val): 根据shape生成一个数组，每个元素值都是val
- np.eye(n): 创建一个正方的n*n单位矩阵，对角线为1，其余为0
- np.ones_like(a): 根据数组a的形状生成一个全1数组
- np.zeros_like(a): 根据数组a的形状生成一个全0数组
- np.full_like(a,val): 根据数组a的形状生成一个数组，每个数组的元素都是val

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
x = np.ones((2,3,4))
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [34]:
x.shape

(2, 3, 4)

## 使用NumPy中其他函数创建ndarray数组
- np.linspace(): 根据起止数据等间距地填充数据，形成数组
- np.concatenate(): 将两个或多个数组合并成一个新的数组

In [35]:
a = np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

In [37]:
b = np.linspace(1,10,4,endpoint = False)
b

array([1.  , 3.25, 5.5 , 7.75])

In [38]:
c = np.concatenate((a,b))
c 

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

# ndarray数组的变换
对于创建后的ndarray数组，可以对其进行维度变换和元素类型变换


In [41]:
a = np.ones((2,3,4),dtype = np.int64)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

# ndarray数组的维度变换
- .reshape(shape): 不改变数组的元素，返回一个shape形状的的数组
- .resize(shape): 与.reshape()功能一致，但修改原数组
- .swapaxes(ax1,ax2): 将数组n个维度中两个维度进行调换
- .flatten(): 对数组进行降维，返回折叠后的一组数组，原数组不变

In [42]:
a = np.ones((2,3,4),dtype = np.int64)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [43]:
a.reshape((3,8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [45]:
a.resize((3,8))
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
a = np.ones((2,3,4),dtype = np.int64)
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [47]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [48]:
b = a.flatten()
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

# ndarray数组的类型的变换

- new_a = a.astype(new_type)

astype()方法一定会创建新的数组(原始数据的一个拷贝)，即使两个类型一致

In [50]:
new_a = a.astype(np.float)
new_a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# 数组to列表的转换

In [51]:
ls = a.tolist()
ls

[[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
 [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]]

In [52]:
type(ls)

list

# 数组的索引和切片
- 索引：获取数组中特定位置元素的过程
- 切片：获取数组元素字集的过程

## 一维数组
与Python的list的索引，切片一样

In [17]:
a  = np.array([9,8,7,6,5])
a[0] # 索引

9

In [18]:
a[1:4:2] # 切片, index4是不在选取范围内的

array([8, 6])

## 多维数组
### 多维数组的索引


In [19]:
a = np.arange(24).reshape((2,3,4)) # 生成一个0~23的一维数组，用reshape把它变形成多维数组
a # 可以理解成两个3*4的matrix

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
a[1,2,3] #第1个matrix的第2行的第3个元素

23

In [21]:
a[0,1,2]

6

In [22]:
a[-1,-2,-3]

17

### 多维数组的切片


In [23]:
a = np.arange(24).reshape((2,3,4)) # 生成一个0~23的一维数组，用reshape把它变形成多维数组
a # 可以理解成两个3*4的matrix

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
a[:,1,-3] 
# ：的意思是不管数组的index，也就是这里的操作是选取所有的数组
# 取所有数组的第1行的第-3个元素


array([ 5, 17])

In [25]:
a[:,1:3,:] # 取所有数组的第1～2行

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
a[:,:,::2] 

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])